const TEXT_SMALL= 12.0;
const TEXT_REGULAR= 16.0;
const TEXT_REGULAR_1X= 18.0;
const TEXT_HEADING = 20.0;
const TEXT_HEADING_1X = 22.0;
const TEXT_HEADING_2X = 24.0;
const TEXT_HEADING_3X = 26.0;

const MARGIN_CARD_SMALL=4.0;
const MARGIN_SMALL = 8.0;
const MARGIN_SMALL_2 = 12.0;
const MARGIN_MEDIUM= 16.0;
const MARGIN_MEDIUM_1 = 18.0;
const MARGIN_MEDIUM_2 = 20.0;
const MARGIN_MEDIUM_3= 22.0;
const MARGIN_LARGE= 24.0;
const MARGIN_LARGE_2=30.0;
const MARGIN_XLARGE= 32.0;
const MARGIN_XXLARGE= 40.0;

const SEAT_TYPE_AVAILABLE="SEAT_TYPE_AVAILABLE";
const SEAT_TYPE_TEXT="SEAT_TYPE_TEXT";
const SEAT_TYPE_TAKEN="SEAT_TYPE_TAKEN";
const SEAT_TYPE_EMPTY="SEAT_TYPE_EMPTY";
const SEAT_TYPE_RESERVED="Reserved";
const SEAT_TYPE_AVAILABLE_TEXT="Available";
const SEAT_TYPE_SELECTION="Your selection";

const WELCOME_ILLUSTRATION_HEIGHT= 300.0;
const WELCOME_ILLUSTRATION_WIDTH= 300.0;
const SOCIAL_MEDIA_ICON_SIZE= 30.0;
const MOVIES_DETAIL_POSTER_HEIGHT=320.0;
const MOVIES_DETAIL_INFO_HEIGHT= 300.0;
const MOVIES_POSTER_ITEM_HEIGHT=300.0;
const MOVIES_POSTER_ITEM_WIDTH=150.0;
const MOVIES_IMAGE_HEIGHT=200.0;
const AVATAR_SIZE=60.0;
const LEADING_ICON_SIZE=30.0;
const TICKET_BARCODE_HEIGHT=250.0;
const TICKET_BARCODE_WIDTH=60.0;

