
//hive type
const HIVE_USER_ID=1;
const HIVE_MOVIE_ID=2;
const HIVE_CREDIT_ID=3;
const HIVE_GENRE_ID=4;
const HIVE_CARD_ID=5;
const HIVE_DATE_TIME = 6;
const HIVE_CINEMA_TIME_SLOT =7;
const HIVE_TIME_SLOT=8;
const HIVE_SNACK_LIST=9;
const HIVE_PAYMENT_ID=10;

//box name
const BOX_NAMES_USER_VO="BOX_NAMES_USER_VO";
const BOX_NAMES_MOVIE_VO="BOX_NAMES_MOVIE_VO";
const BOX_NAMES_CREDIT_VO="BOX_NAMES_CREDIT_VO";
const BOX_NAMES_GENRE_VO="BOX_NAMES_GENRE_VO";
const BOX_NAMES_DATE_TIME_VO="BOX_NAMES_DATE_TIME_VO";
const BOX_NAMES_CINEMA_TIME_SLOT_VO="BOX_NAMES_CINEMA_TIME_SLOT_VO";
const BOX_NAMES_TIME_SLOT_VO="BOX_NAMES_TIME_SLOT_VO";
const BOX_NAMES_SNACK_VO="BOX_NAMES_SNACK_VO";
const BOX_NAMES_CARD_VO="BOX_NAMES_CARD_VO";
const BOX_NAMES_PAYMENT_VO="BOX_NAMES_PAYMENT_VO";